env:
 global:
   - ADB_INSTALL_TIMEOUT=8 # 8 minutes
language: android
android:
  components:
    - tools
    - build-tools-27.0.2
    - android-23
    - android-28
jdk:
  - oraclejdk8
script:
  - chmod +x ./gradlew
  - ./gradlew
licenses:
    - 'android-sdk-license-.+'
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
before_install:
  - yes | sdkmanager "platforms;android-28"
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
sudo: required
after_success:
  - bash <(curl -s https://codecov.io/bash)